Copy-Item 'frontend_new\*HomePage*.jsx' -Destination 'frontend/src/pages/HomePage.jsx' -Force
Copy-Item 'frontend_new\*LoginPage*.jsx' -Destination 'frontend/src/pages/LoginPage.jsx' -Force
Copy-Item 'frontend_new\*RegisterPage*.jsx' -Destination 'frontend/src/pages/RegisterPage.jsx' -Force
Copy-Item 'frontend_new\*SleepChart*.jsx' -Destination 'frontend/src/components/SleepChart.jsx' -Force
Copy-Item 'frontend_new\*DataVisualization*.jsx' -Destination 'frontend/src/components/DataVisualization.jsx' -Force
Copy-Item 'frontend_new\*AlarmHistory*.jsx' -Destination 'frontend/src/components/AlarmHistory.jsx' -Force
Copy-Item 'frontend_new\*PrivateRoute*.jsx' -Destination 'frontend/src/components/PrivateRoute.jsx' -Force
Copy-Item 'frontend_new\*ShootingStars*.jsx' -Destination 'frontend/src/components/ShootingStars.jsx' -Force
Copy-Item 'frontend_new\*ShootingStars*.css' -Destination 'frontend/src/components/ShootingStars.css' -Force
Copy-Item 'frontend_new\*App*.jsx' -Destination 'frontend/src/App.jsx' -Force
Copy-Item 'frontend_new\*index*.html' -Destination 'frontend/index.html' -Force
